In [1]:
import pandas as pd
import numpy as np
import holidays

In [2]:
df = pd.DataFrame({
    "Date": pd.date_range(start="2024-01-01", end="2024-12-31", freq="D")
})

df.head()

        Date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

In [3]:
df["Date"] = pd.to_datetime(df["Date"])

In [4]:
df["day_of_week"] = df["Date"].dt.day_name()

In [5]:
df["month"] = df["Date"].dt.month_name()

In [6]:
df["day_num"] = df["Date"].dt.dayofweek
df["month_num"] = df["Date"].dt.month

In [7]:
pk_holidays = holidays.Pakistan()

df["is_holiday"] = df["Date"].dt.date.isin(pk_holidays).astype(int)

In [8]:
day_encoded = pd.get_dummies(df["day_of_week"], prefix="day")

In [9]:
month_encoded = pd.get_dummies(df["month"], prefix="month")

In [10]:
df = pd.concat([df, day_encoded, month_encoded], axis=1)

In [11]:
df.head()

,Date,day_of_week,month,day_num,month_num,is_holiday,day_Friday,day_Monday,day_Saturday,day_Sunday,...,month_December,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September
0,2024-01-01,Monday,January,0,1,0,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
1,2024-01-02,Tuesday,January,1,1,0,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,2024-01-03,Wednesday,January,2,1,0,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,2024-01-04,Thursday,January,3,1,0,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,2024-01-05,Friday,January,4,1,0,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [13]:
df.to_csv("feature_engineering_output.csv", index=False)